create table if not exists app_user (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password_hash varchar(100) not null,
    display_name varchar(100) not null,
    role varchar(32) not null,
    site_scope varchar(255) not null,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp
);

create table if not exists ai_agent_provider_config (
    user_id bigint primary key,
    base_url varchar(500) not null,
    model varchar(100) not null,
    encrypted_api_key varchar(2048),
    created_at timestamp not null,
    updated_at timestamp not null,
    foreign key (user_id) references app_user(id) on delete cascade
);

create table if not exists site (
    id bigint generated by default as identity primary key,
    code varchar(32) not null unique,
    name varchar(120) not null,
    address varchar(255),
    status varchar(20) not null,
    updated_at timestamp not null
);

create table if not exists zone (
    id bigint generated by default as identity primary key,
    site_id bigint not null,
    code varchar(32) not null unique,
    name varchar(100) not null,
    status varchar(20) not null,
    map_x decimal(6,3) not null,
    map_y decimal(6,3) not null,
    map_width decimal(6,3) not null,
    map_height decimal(6,3) not null,
    foreign key (site_id) references site(id)
);

create table if not exists device (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name varchar(120) not null,
    type varchar(32) not null,
    site_id bigint not null,
    zone_id bigint not null,
    location varchar(255),
    enabled boolean not null default true,
    connection_status varchar(20) not null,
    last_reported_at timestamp,
    config_json clob,
    foreign key (site_id) references site(id),
    foreign key (zone_id) references zone(id)
);
create index if not exists idx_device_connection_heartbeat on device(connection_status, enabled, last_reported_at, id);

create table if not exists telemetry (
    id bigint generated by default as identity primary key,
    message_id varchar(80) not null,
    device_id bigint not null,
    metric_code varchar(64) not null,
    metric_value decimal(18,4) not null,
    unit varchar(24),
    collected_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    constraint uq_telemetry_message_metric unique (message_id, metric_code),
    foreign key (device_id) references device(id)
);
create index if not exists idx_telemetry_device_time on telemetry(device_id, collected_at);
create index if not exists idx_telemetry_device_metric_time on telemetry(device_id, metric_code, collected_at, id);

create table if not exists alarm_rule (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    source_type varchar(32) not null,
    metric_code varchar(64) not null,
    operator varchar(8) not null,
    threshold_value decimal(18,4) not null,
    severity varchar(16) not null,
    scope_type varchar(16) not null,
    scope_id bigint,
    enabled boolean not null default true,
    suppression_seconds int not null default 300,
    updated_at timestamp not null
);
create index if not exists idx_alarm_rule_scope on alarm_rule(scope_type, scope_id, id);
create index if not exists idx_alarm_rule_metric_enabled on alarm_rule(metric_code, enabled);

create table if not exists alarm (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    site_id bigint not null,
    zone_id bigint not null,
    device_id bigint,
    rule_id bigint,
    source_type varchar(32) not null,
    severity varchar(16) not null,
    title varchar(160) not null,
    description varchar(500) not null,
    status varchar(20) not null,
    first_occurred_at timestamp not null,
    last_occurred_at timestamp not null,
    occurrences int not null default 1,
    foreign key (site_id) references site(id),
    foreign key (zone_id) references zone(id),
    foreign key (device_id) references device(id),
    foreign key (rule_id) references alarm_rule(id)
);
create index if not exists idx_alarm_site_status_time on alarm(site_id, status, last_occurred_at);
create index if not exists idx_alarm_site_zone_time on alarm(site_id, zone_id, last_occurred_at, id);
create index if not exists idx_alarm_device_source_status on alarm(device_id, source_type, status, id);

create table if not exists alarm_action (
    id bigint generated by default as identity primary key,
    alarm_id bigint not null,
    operator_id bigint not null,
    action varchar(24) not null,
    from_status varchar(20) not null,
    to_status varchar(20) not null,
    note varchar(500),
    created_at timestamp not null,
    foreign key (alarm_id) references alarm(id),
    foreign key (operator_id) references app_user(id)
);

create table if not exists camera (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name varchar(120) not null,
    site_id bigint not null,
    zone_id bigint not null,
    online boolean not null,
    stream_url varchar(500),
    last_frame_at timestamp,
    foreign key (site_id) references site(id),
    foreign key (zone_id) references zone(id)
);
create index if not exists idx_camera_site_code on camera(site_id, code, id);
create index if not exists idx_camera_site_zone on camera(site_id, zone_id);

create table if not exists ai_risk (
    id bigint generated by default as identity primary key,
    camera_id bigint not null,
    site_id bigint not null,
    zone_id bigint not null,
    risk_type varchar(64) not null,
    confidence decimal(6,4) not null,
    model_version varchar(64) not null,
    occurred_at timestamp not null,
    evidence_url varchar(500),
    status varchar(20) not null,
    review_note varchar(500),
    reviewed_by bigint,
    reviewed_at timestamp,
    foreign key (camera_id) references camera(id),
    foreign key (site_id) references site(id),
    foreign key (zone_id) references zone(id)
);

create table if not exists sprinkler_task (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    site_id bigint not null,
    zone_id bigint not null,
    trigger_type varchar(24) not null,
    reason varchar(500) not null,
    status varchar(24) not null,
    planned_at timestamp not null,
    started_at timestamp,
    ended_at timestamp,
    command_id varchar(64),
    failure_reason varchar(500),
    created_by bigint not null,
    foreign key (site_id) references site(id),
    foreign key (zone_id) references zone(id),
    foreign key (created_by) references app_user(id)
);
create index if not exists idx_sprinkler_task_site_time on sprinkler_task(site_id, planned_at, id);
create index if not exists idx_sprinkler_task_site_status_time on sprinkler_task(site_id, status, planned_at, id);
create index if not exists idx_sprinkler_task_site_zone_time on sprinkler_task(site_id, zone_id, planned_at, id);

create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    username varchar(50) not null,
    action varchar(80) not null,
    object_type varchar(50) not null,
    object_id varchar(80),
    detail varchar(1000),
    trace_id varchar(64),
    created_at timestamp not null
);

create table if not exists ai_agent_conversation (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    site_id bigint not null,
    title varchar(80) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    foreign key (user_id) references app_user(id),
    foreign key (site_id) references site(id)
);
create index if not exists idx_ai_agent_conversation_owner_time
    on ai_agent_conversation(user_id, site_id, updated_at, id);

create table if not exists ai_agent_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    role varchar(16) not null,
    content clob not null,
    provider_mode varchar(32),
    provider_model varchar(100),
    created_at timestamp not null,
    foreign key (conversation_id) references ai_agent_conversation(id)
);
create index if not exists idx_ai_agent_message_conversation_time
    on ai_agent_message(conversation_id, created_at, id);

create table if not exists knowledge_document (
    id bigint generated by default as identity primary key,
    site_id bigint not null,
    title varchar(160) not null,
    category varchar(80) not null,
    source_reference varchar(500),
    content clob not null,
    version int not null default 1,
    status varchar(24) not null,
    created_by bigint not null,
    reviewed_by bigint,
    review_note varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    reviewed_at timestamp,
    foreign key (site_id) references site(id),
    foreign key (created_by) references app_user(id),
    foreign key (reviewed_by) references app_user(id)
);
create index if not exists idx_knowledge_document_site_status_time
    on knowledge_document(site_id, status, updated_at, id);

create table if not exists report_template (
    id bigint generated by default as identity primary key,
    site_id bigint not null,
    name varchar(120) not null,
    description varchar(500),
    body_template clob not null,
    enabled boolean not null default true,
    created_by bigint not null,
    updated_by bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    foreign key (site_id) references site(id),
    foreign key (created_by) references app_user(id),
    foreign key (updated_by) references app_user(id)
);
create index if not exists idx_report_template_site_enabled_time
    on report_template(site_id, enabled, updated_at, id);

create table if not exists safety_report (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    site_id bigint not null,
    template_id bigint,
    title varchar(160) not null,
    content clob not null,
    status varchar(24) not null,
    created_by bigint not null,
    reviewed_by bigint,
    review_note varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    reviewed_at timestamp,
    foreign key (site_id) references site(id),
    foreign key (template_id) references report_template(id),
    foreign key (created_by) references app_user(id),
    foreign key (reviewed_by) references app_user(id)
);
create index if not exists idx_safety_report_site_status_time
    on safety_report(site_id, status, updated_at, id);

create table if not exists push_channel (
    id bigint generated by default as identity primary key,
    site_id bigint not null,
    name varchar(120) not null,
    type varchar(24) not null,
    endpoint_url varchar(500),
    credential_env_name varchar(100),
    enabled boolean not null default true,
    created_by bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    foreign key (site_id) references site(id),
    foreign key (created_by) references app_user(id)
);
create index if not exists idx_push_channel_site_enabled
    on push_channel(site_id, enabled, id);

create table if not exists push_delivery (
    id bigint generated by default as identity primary key,
    report_id bigint not null,
    channel_id bigint not null,
    status varchar(24) not null,
    attempt_count int not null default 0,
    http_status int,
    error_message varchar(500),
    created_by bigint not null,
    created_at timestamp not null,
    completed_at timestamp,
    foreign key (report_id) references safety_report(id),
    foreign key (channel_id) references push_channel(id),
    foreign key (created_by) references app_user(id)
);
create index if not exists idx_push_delivery_report_time
    on push_delivery(report_id, created_at, id);
